"""Release-source verification and narrowly scoped legacy code-overlay removal.

Does not change database, catalog, credentials, volumes or inference configuration.
The only removable mounts are literal read-only code mounts generated by the old
scripts/update_ec2.py. Unknown/custom mounts remain and cause a digest mismatch.
"""
import argparse
import hashlib
import json
from pathlib import Path
import sys

CODE_MOUNTS = frozenset((
    'web', 'retailops', 'retailops_providers.py', 'agent_protocol.py',
    'retailops_agent.py', 'retailops_tools.py', 'retailops_conversation.py',
    'retailops_mcp_server.py', 'inference_proxy.py', 'retailops_public.py',
))


def strip_legacy_code_mounts(source):
    lines = []
    for line in source.splitlines(keepends=True):
        value = line.strip()
        if value.startswith('- '):
            value = value[2:].split(' #', 1)[0].strip().strip('\"\'')
            if any(value == f'/opt/retailops/patches/{name}:/app/{name}:ro'
                   for name in CODE_MOUNTS):
                continue
        lines.append(line)
    return ''.join(lines)


def source_digest(root):
    root = Path(root)
    paths = list(root.glob('*.py')) + list((root / 'retailops').rglob('*.py'))
    paths += [p for p in (root / 'web').glob('*') if p.is_file()]
    if not paths or not (root / 'retailops_providers.py').is_file():
        raise ValueError('Release source is incomplete')
    manifest = {p.relative_to(root).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
                for p in sorted(paths)}
    return hashlib.sha256(json.dumps(manifest, sort_keys=True, separators=(',', ':')).encode()).hexdigest()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('operation', choices=('strip', 'digest'))
    args = parser.parse_args()
    if args.operation == 'strip':
        sys.stdout.write(strip_legacy_code_mounts(sys.stdin.read()))
    else:
        print(source_digest(Path(__file__).resolve().parents[1]))


if __name__ == '__main__':
    main()
